import { Restaurant } from '../components/RestaurantCard';

export const FALLBACK_RESTAURANTS: Restaurant[] = [
      {
            id: '1',
            restaurant_id: '1',
            name: 'Sobo Bite House',
            city: 'Mumbai',
            area: 'Colaba',
            lat: 18.922,
            lng: 72.833,
            cuisines: ['Indian', 'Cafe'],
            cuisine_tags: ['Indian', 'Cafe'],
            visited: true,
            total_dishes_reviewed: 18,
            top_picks: ['Vada Pav', 'Misal Pav', 'Cutting Chai'],
            meta: {
                  first_visit: '2026-01-12',
                  last_visit: '2026-04-21',
            },
            rating: 4.7,
            price_range: 1,
            hero_image_url: null,
      },
      {
            id: '2',
            restaurant_id: '2',
            name: 'Marine Drive Kitchen',
            city: 'Mumbai',
            area: 'Marine Lines',
            lat: 18.944,
            lng: 72.823,
            cuisines: ['Seafood', 'North Indian'],
            cuisine_tags: ['Seafood', 'North Indian'],
            visited: true,
            total_dishes_reviewed: 12,
            top_picks: ['Butter Garlic Prawns', 'Fish Thali', 'Solkadhi'],
            meta: {
                  first_visit: '2026-02-03',
                  last_visit: '2026-04-28',
            },
            rating: 4.5,
            price_range: 2,
            hero_image_url: null,
      },
      {
            id: '3',
            restaurant_id: '3',
            name: 'Dishes & Co.',
            city: 'Mumbai',
            area: 'Fort',
            lat: 18.932,
            lng: 72.834,
            cuisines: ['Modern Indian', 'Desserts'],
            cuisine_tags: ['Modern Indian', 'Desserts'],
            visited: false,
            total_dishes_reviewed: 9,
            top_picks: ['Truffle Naan', 'Saffron Kheer', 'Bombay Sandwich'],
            meta: {
                  first_visit: '2026-03-10',
                  last_visit: '2026-04-18',
            },
            rating: 4.3,
            price_range: 3,
            hero_image_url: null,
      },
      {
            id: '4',
            restaurant_id: '4',
            name: 'Snack Street',
            city: 'Mumbai',
            area: 'Churchgate',
            lat: 18.936,
            lng: 72.828,
            cuisines: ['Street Food'],
            cuisine_tags: ['Street Food'],
            visited: true,
            total_dishes_reviewed: 14,
            top_picks: ['Pav Bhaji', 'Sev Puri', 'Bhel Puri'],
            meta: {
                  first_visit: '2026-01-28',
                  last_visit: '2026-05-01',
            },
            rating: 4.8,
            price_range: 1,
            hero_image_url: null,
      },
];